language: ruby
cache: bundler
rvm:
  - 2.3.0
env:
  - DB=sqlite3
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
before_script:
  - cp config/database.travis.yml config/database.yml
notifications:
  email: false