# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 446c8f257f693d41270627e9a33f45fdd0274aa1bd08f63b846adf4173906a9da8c9330ada1f190e8be8babb4dc073208c2119885bcab727e7df40b58e251689

test:
  secret_key_base: a83b20c4b161150a0bd182ded1f2e7bd3452a026835a14263a0b97051175000b36cb73eab61e34984a299cfc72ec3b2aeecd8d3543cb88e8883715a45bb1088e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
